### ISSUE TITLE
Merge cmake into dev

### ISSUE THREAD

**Issue by ihumphrey** [DOI-USGS/ISIS3#457]
_Prerequisites_:
- [ ] bundle xyz merged into cmake -- #455 
- [ ] isis3_mosaic_tracking merged into cmake -- #458 
- [x] development applications integrated into cmake -- #461 
- [ ] outstanding PRs needed in release merged into dev
  - [ ] PostgreSQL -- #440 
  - [x] Clementine -- #450 
  - [ ] isis3 version update -- #438 
  - [ ] **continue through rest of outstanding PRs...**

_Requirements_:
- [x] merge dev into cmake
- [x] builds and tests successfully on:
  - [x] Fedora28
  - [x] Ubuntu18.04
  - [x] macOS10.13
- [x] PR cmake into dev
  - [x] describe the changes listed above in the PR
  - [x] reference appropriate GitHub issues
  - [ ] reference Redmine issues (5520 -- integrate cmake ; 5521 -- integrate development applications)
  - [ ] reference Redmine issues for process mosaic tracking -- **add ticket number here**
  - [ ] reference Redmine issues for bundle xyz -- **add ticket number here**

There is a lot of housekeeping to do because of simultaneously creating new infrastructure issues with GitHub issues and addressing existing Redmine issues.

**Comment by kaitlyndlee** [comment]
Other than the tests that are failing on nightly and UserInterface (this unit test is randomly passing and failing and I am not sure why), the merge is good on MacOS 10.13.

**Comment by ihumphrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge cmake into dev](https://trello.com/c/cTFh5aUI/138-merge-cmake-into-dev)

**Comment by jessemapel** [comment]
@ihumphrey-usgs This is done now correct?

**Comment by ihumphrey** [comment]
@jessemapel Yes, I'll go ahead and close this
