### ISSUE TITLE
Get Clean Jenkins Dev Tests

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ISIS3#4666]
**ISIS version(s) affected**: dev

**Description**  

Several test are failing regularly and haven't been addressed. These have been disabled and we need to fix them in order to get clean tests. 

These include: 
 1. edrget app test failures
 2. TGO cat test failures
 3. ObervationPair fixture failing on setup

**How to reproduce**  

Revert changes in https://github.com/USGS-Astrogeology/ISIS3/pull/4664 and run gtest

**Possible Solution**  

- [ ] remove edrget application, tests and documentation (#4665)
- [ ] Somehow fix the kernels used by the TGO tests, TGO category tests seem to fail because of changing kernels  (#4661)
- [x] fix ObservationPair segfaults (context #4609)
